## If you don?t have a schema-h2.sql file in resources, but a schema-h2.sql file instead, uncomment this:
## spring.sql.init.platform=h2
#
## H2 console
#spring.h2.console.enabled=true
#
## DataSource naming (as in book)
#spring.datasource.generate-unique-name=false
#spring.datasource.name=test-db
#
## IMPORTANT for non-embedded DB init; optional for H2 but ok to keep:
#spring.sql.init.mode=always


# H2
# spring.h2.console.enabled=true

# REST
#spring.data.rest.base-path=/api

# H2 (replaces PostgreSQL for main runtime)
spring.datasource.url=jdbc:h2:mem:test-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# RabbitMQ
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Docker Compose
spring.docker.compose.file=./docker-compose.yaml

# JPA
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#
## Docker Compose
#spring.docker.compose.file=./docker-compose.yaml
#










## SQL init
#spring.sql.init.mode=always
#spring.sql.init.platform=postgresql
#
## Postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5434/test-db
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver
