
## Actuator ? expose all endpoints
management.endpoints.web.exposure.include=*

## Actuator Info
management.info.env.enabled=true
info.application.name=${spring.application.name}
info.developer.name=Temirlan
info.developer.email=temirlan@email.com
info.api.version=1.0

## Git info mode
management.info.git.mode=full

## Shutdown endpoint
management.endpoint.shutdown.enabled=true

## Health details
management.endpoint.health.show-details=when_authorized
management.endpoint.health.roles=ACTUATOR

## Health status order (custom EVENTS-DOWN first)
management.endpoint.health.status.order=events-down,fatal,down,out-of-service,unknown,up
